### ISSUE TITLE
Add documentation URL to repo description

### ISSUE THREAD

**Issue by GenevieveBuckley** [jni/affinder#68]
This is different to https://github.com/jni/affinder/pull/67 (but it is related).

@jni you can add a URL to the right hand sidebar description on your repo page. Can you add the documentation url there? https://jni.github.io/affinder/

You have to look for the little gear icon in the right hand sidebar,  next to the "About" repo info. You click it to edit the repo description and url.
<img width="1350" alt="Screen Shot 2023-04-20 at 10 04 21 am" src="https://user-images.githubusercontent.com/30920819/233225830-09b254b9-adfa-4f3d-ae81-c9d1726179f9.png">

Then there's a spot you can add the URL

<img width="1327" alt="Screen Shot 2023-04-20 at 10 04 38 am" src="https://user-images.githubusercontent.com/30920819/233225868-26bd16aa-9a3c-4d78-be4c-06c0e6290582.png">

**Comment by jni** [comment]
Done, thanks! 🙏
